// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRm2PkYlR8cvc3VI4QSz5Ew6p20qmvoME',
    appId: '1:951542270078:web:8e0ecf9556924b28dcb02f',
    messagingSenderId: '951542270078',
    projectId: 'talkrr-chat-app',
    authDomain: 'talkrr-chat-app.firebaseapp.com',
    storageBucket: 'talkrr-chat-app.appspot.com',
    measurementId: 'G-LE35NPLDT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_lre2WEIEeUVJ_Wn5U3OE-YLSarubPk',
    appId: '1:951542270078:android:bcb6c1babb047247dcb02f',
    messagingSenderId: '951542270078',
    projectId: 'talkrr-chat-app',
    storageBucket: 'talkrr-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcUXiZ4Z-ehXj92EJI3qvMXufm4wQ2lhs',
    appId: '1:951542270078:ios:fb2d1e870b25544ddcb02f',
    messagingSenderId: '951542270078',
    projectId: 'talkrr-chat-app',
    storageBucket: 'talkrr-chat-app.appspot.com',
    iosBundleId: 'com.example.talkrrChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcUXiZ4Z-ehXj92EJI3qvMXufm4wQ2lhs',
    appId: '1:951542270078:ios:fb2d1e870b25544ddcb02f',
    messagingSenderId: '951542270078',
    projectId: 'talkrr-chat-app',
    storageBucket: 'talkrr-chat-app.appspot.com',
    iosBundleId: 'com.example.talkrrChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRm2PkYlR8cvc3VI4QSz5Ew6p20qmvoME',
    appId: '1:951542270078:web:2bd43cdaf800abc4dcb02f',
    messagingSenderId: '951542270078',
    projectId: 'talkrr-chat-app',
    authDomain: 'talkrr-chat-app.firebaseapp.com',
    storageBucket: 'talkrr-chat-app.appspot.com',
    measurementId: 'G-K2J2WF1D0H',
  );
}
